// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/node.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRole int32

const (
	NodeRole_NODE_ROLE_UNSPECIFIED NodeRole = 0
	NodeRole_NODE_ROLE_MASTER      NodeRole = 1
	NodeRole_NODE_ROLE_STORAGE     NodeRole = 2
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "NODE_ROLE_UNSPECIFIED",
		1: "NODE_ROLE_MASTER",
		2: "NODE_ROLE_STORAGE",
	}
	NodeRole_value = map[string]int32{
		"NODE_ROLE_UNSPECIFIED": 0,
		"NODE_ROLE_MASTER":      1,
		"NODE_ROLE_STORAGE":     2,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 1
	NodeStatus_NODE_STATUS_OFFLINE     NodeStatus = 2
	NodeStatus_NODE_STATUS_STARTING    NodeStatus = 3
	NodeStatus_NODE_STATUS_STOPPING    NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_OFFLINE",
		3: "NODE_STATUS_STARTING",
		4: "NODE_STATUS_STOPPING",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ONLINE":      1,
		"NODE_STATUS_OFFLINE":     2,
		"NODE_STATUS_STARTING":    3,
		"NODE_STATUS_STOPPING":    4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

type LockStatus int32

const (
	LockStatus_LOCK_STATUS_UNSPECIFIED LockStatus = 0
	LockStatus_LOCK_STATUS_PENDING     LockStatus = 1
	LockStatus_LOCK_STATUS_GRANTED     LockStatus = 2
	LockStatus_LOCK_STATUS_RELEASED    LockStatus = 3
)

// Enum value maps for LockStatus.
var (
	LockStatus_name = map[int32]string{
		0: "LOCK_STATUS_UNSPECIFIED",
		1: "LOCK_STATUS_PENDING",
		2: "LOCK_STATUS_GRANTED",
		3: "LOCK_STATUS_RELEASED",
	}
	LockStatus_value = map[string]int32{
		"LOCK_STATUS_UNSPECIFIED": 0,
		"LOCK_STATUS_PENDING":     1,
		"LOCK_STATUS_GRANTED":     2,
		"LOCK_STATUS_RELEASED":    3,
	}
)

func (x LockStatus) Enum() *LockStatus {
	p := new(LockStatus)
	*p = x
	return p
}

func (x LockStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[2].Descriptor()
}

func (LockStatus) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[2]
}

func (x LockStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockStatus.Descriptor instead.
func (LockStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

// Empty response for RPCs that don't return data
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID as string
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Role          NodeRole               `protobuf:"varint,4,opt,name=role,proto3,enum=dfs.NodeRole" json:"role,omitempty"`
	Status        NodeStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=dfs.NodeStatus" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	LastHeartbeat *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_NODE_ROLE_UNSPECIFIED
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *NodeInfo) GetLastHeartbeat() *timestamp.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type ElectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"` // UUID of sender
	NodeInfo      *NodeInfo              `protobuf:"bytes,2,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionRequest) Reset() {
	*x = ElectionRequest{}
	mi := &file_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionRequest) ProtoMessage() {}

func (x *ElectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionRequest.ProtoReflect.Descriptor instead.
func (*ElectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *ElectionRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *ElectionRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *ElectionRequest) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type ElectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OK message - acknowledges election from lower priority node
	FromId        string `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionResponse) Reset() {
	*x = ElectionResponse{}
	mi := &file_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionResponse) ProtoMessage() {}

func (x *ElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionResponse.ProtoReflect.Descriptor instead.
func (*ElectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *ElectionResponse) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *ElectionResponse) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type CoordinatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"` // UUID of new coordinator
	LogicalTime   int32                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorRequest) Reset() {
	*x = CoordinatorRequest{}
	mi := &file_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorRequest) ProtoMessage() {}

func (x *CoordinatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *CoordinatorRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *CoordinatorRequest) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoveryRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *DiscoveryRequest) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*NodeInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *DiscoveryResponse) GetPeers() []*NodeInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *DiscoveryResponse) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type NodeJoinedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeJoinedRequest) Reset() {
	*x = NodeJoinedRequest{}
	mi := &file_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeJoinedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoinedRequest) ProtoMessage() {}

func (x *NodeJoinedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoinedRequest.ProtoReflect.Descriptor instead.
func (*NodeJoinedRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *NodeJoinedRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *NodeJoinedRequest) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type NodeLeftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLeftRequest) Reset() {
	*x = NodeLeftRequest{}
	mi := &file_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLeftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLeftRequest) ProtoMessage() {}

func (x *NodeLeftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLeftRequest.ProtoReflect.Descriptor instead.
func (*NodeLeftRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *NodeLeftRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeLeftRequest) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type LockRequestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // UUID of requesting node
	LogicalTime   int32                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	Status        LockStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=dfs.LockStatus" json:"status,omitempty"`
	RequestedAt   *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequestMsg) Reset() {
	*x = LockRequestMsg{}
	mi := &file_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequestMsg) ProtoMessage() {}

func (x *LockRequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequestMsg.ProtoReflect.Descriptor instead.
func (*LockRequestMsg) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *LockRequestMsg) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *LockRequestMsg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LockRequestMsg) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *LockRequestMsg) GetStatus() LockStatus {
	if x != nil {
		return x.Status
	}
	return LockStatus_LOCK_STATUS_UNSPECIFIED
}

func (x *LockRequestMsg) GetRequestedAt() *timestamp.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type LockAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockAck) Reset() {
	*x = LockAck{}
	mi := &file_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAck) ProtoMessage() {}

func (x *LockAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAck.ProtoReflect.Descriptor instead.
func (*LockAck) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *LockAck) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *LockAck) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *LockAck) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type LockAcquiredMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockAcquiredMsg) Reset() {
	*x = LockAcquiredMsg{}
	mi := &file_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAcquiredMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAcquiredMsg) ProtoMessage() {}

func (x *LockAcquiredMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAcquiredMsg.ProtoReflect.Descriptor instead.
func (*LockAcquiredMsg) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *LockAcquiredMsg) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *LockAcquiredMsg) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *LockAcquiredMsg) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type LockReleaseMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockReleaseMsg) Reset() {
	*x = LockReleaseMsg{}
	mi := &file_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockReleaseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockReleaseMsg) ProtoMessage() {}

func (x *LockReleaseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockReleaseMsg.ProtoReflect.Descriptor instead.
func (*LockReleaseMsg) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *LockReleaseMsg) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *LockReleaseMsg) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *LockReleaseMsg) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type LockAbortMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockAbortMsg) Reset() {
	*x = LockAbortMsg{}
	mi := &file_proto_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAbortMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAbortMsg) ProtoMessage() {}

func (x *LockAbortMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAbortMsg.ProtoReflect.Descriptor instead.
func (*LockAbortMsg) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{14}
}

func (x *LockAbortMsg) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *LockAbortMsg) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type FileDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDeleteRequest) Reset() {
	*x = FileDeleteRequest{}
	mi := &file_proto_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteRequest) ProtoMessage() {}

func (x *FileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteRequest.ProtoReflect.Descriptor instead.
func (*FileDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{15}
}

func (x *FileDeleteRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileDeleteRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *FileDeleteRequest) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type FileStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,6,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStoreRequest) Reset() {
	*x = FileStoreRequest{}
	mi := &file_proto_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStoreRequest) ProtoMessage() {}

func (x *FileStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStoreRequest.ProtoReflect.Descriptor instead.
func (*FileStoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{16}
}

func (x *FileStoreRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileStoreRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileStoreRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileStoreRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileStoreRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileStoreRequest) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type FileStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStoreResponse) Reset() {
	*x = FileStoreResponse{}
	mi := &file_proto_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStoreResponse) ProtoMessage() {}

func (x *FileStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStoreResponse.ProtoReflect.Descriptor instead.
func (*FileStoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{17}
}

func (x *FileStoreResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileStoreResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type MetadataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataReq) Reset() {
	*x = MetadataReq{}
	mi := &file_proto_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataReq) ProtoMessage() {}

func (x *MetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataReq.ProtoReflect.Descriptor instead.
func (*MetadataReq) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{18}
}

func (x *MetadataReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MetadataReq) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *MetadataReq) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type NodeFileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeFileMetadata) Reset() {
	*x = NodeFileMetadata{}
	mi := &file_proto_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeFileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeFileMetadata) ProtoMessage() {}

func (x *NodeFileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeFileMetadata.ProtoReflect.Descriptor instead.
func (*NodeFileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{19}
}

func (x *NodeFileMetadata) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *NodeFileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *NodeFileMetadata) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *NodeFileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *NodeFileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type MetadataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Files         []*NodeFileMetadata    `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,4,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResp) Reset() {
	*x = MetadataResp{}
	mi := &file_proto_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResp) ProtoMessage() {}

func (x *MetadataResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResp.ProtoReflect.Descriptor instead.
func (*MetadataResp) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{20}
}

func (x *MetadataResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MetadataResp) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetadataResp) GetFiles() []*NodeFileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *MetadataResp) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type ReplicateFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	SourceNode    string                 `protobuf:"bytes,4,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	TargetNodes   []string               `protobuf:"bytes,5,rep,name=target_nodes,json=targetNodes,proto3" json:"target_nodes,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,6,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateFileReq) Reset() {
	*x = ReplicateFileReq{}
	mi := &file_proto_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateFileReq) ProtoMessage() {}

func (x *ReplicateFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateFileReq.ProtoReflect.Descriptor instead.
func (*ReplicateFileReq) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{21}
}

func (x *ReplicateFileReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ReplicateFileReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReplicateFileReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ReplicateFileReq) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *ReplicateFileReq) GetTargetNodes() []string {
	if x != nil {
		return x.TargetNodes
	}
	return nil
}

func (x *ReplicateFileReq) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type APIFileDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,4,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIFileDeleteReq) Reset() {
	*x = APIFileDeleteReq{}
	mi := &file_proto_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIFileDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIFileDeleteReq) ProtoMessage() {}

func (x *APIFileDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIFileDeleteReq.ProtoReflect.Descriptor instead.
func (*APIFileDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{22}
}

func (x *APIFileDeleteReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *APIFileDeleteReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *APIFileDeleteReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *APIFileDeleteReq) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type APIFileDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,4,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIFileDeleteResp) Reset() {
	*x = APIFileDeleteResp{}
	mi := &file_proto_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIFileDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIFileDeleteResp) ProtoMessage() {}

func (x *APIFileDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIFileDeleteResp.ProtoReflect.Descriptor instead.
func (*APIFileDeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{23}
}

func (x *APIFileDeleteResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *APIFileDeleteResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *APIFileDeleteResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *APIFileDeleteResp) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type StorageNodeAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // ip:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageNodeAddr) Reset() {
	*x = StorageNodeAddr{}
	mi := &file_proto_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageNodeAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageNodeAddr) ProtoMessage() {}

func (x *StorageNodeAddr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageNodeAddr.ProtoReflect.Descriptor instead.
func (*StorageNodeAddr) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{24}
}

func (x *StorageNodeAddr) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StorageNodeAddr) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type StreamUploadInitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	FromId        string                 `protobuf:"bytes,6,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,7,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUploadInitReq) Reset() {
	*x = StreamUploadInitReq{}
	mi := &file_proto_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUploadInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUploadInitReq) ProtoMessage() {}

func (x *StreamUploadInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUploadInitReq.ProtoReflect.Descriptor instead.
func (*StreamUploadInitReq) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{25}
}

func (x *StreamUploadInitReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamUploadInitReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StreamUploadInitReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StreamUploadInitReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *StreamUploadInitReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StreamUploadInitReq) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *StreamUploadInitReq) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type StreamUploadReadyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StorageNodes  []*StorageNodeAddr     `protobuf:"bytes,3,rep,name=storage_nodes,json=storageNodes,proto3" json:"storage_nodes,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,6,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUploadReadyResp) Reset() {
	*x = StreamUploadReadyResp{}
	mi := &file_proto_node_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUploadReadyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUploadReadyResp) ProtoMessage() {}

func (x *StreamUploadReadyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUploadReadyResp.ProtoReflect.Descriptor instead.
func (*StreamUploadReadyResp) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{26}
}

func (x *StreamUploadReadyResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamUploadReadyResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamUploadReadyResp) GetStorageNodes() []*StorageNodeAddr {
	if x != nil {
		return x.StorageNodes
	}
	return nil
}

func (x *StreamUploadReadyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamUploadReadyResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StreamUploadReadyResp) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type StreamDownloadInitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	FromId        string                 `protobuf:"bytes,4,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,5,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDownloadInitReq) Reset() {
	*x = StreamDownloadInitReq{}
	mi := &file_proto_node_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDownloadInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDownloadInitReq) ProtoMessage() {}

func (x *StreamDownloadInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDownloadInitReq.ProtoReflect.Descriptor instead.
func (*StreamDownloadInitReq) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{27}
}

func (x *StreamDownloadInitReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamDownloadInitReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StreamDownloadInitReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *StreamDownloadInitReq) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *StreamDownloadInitReq) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type StreamDownloadReadyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StorageAddr   string                 `protobuf:"bytes,2,opt,name=storage_addr,json=storageAddr,proto3" json:"storage_addr,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,8,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDownloadReadyResp) Reset() {
	*x = StreamDownloadReadyResp{}
	mi := &file_proto_node_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDownloadReadyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDownloadReadyResp) ProtoMessage() {}

func (x *StreamDownloadReadyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDownloadReadyResp.ProtoReflect.Descriptor instead.
func (*StreamDownloadReadyResp) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{28}
}

func (x *StreamDownloadReadyResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamDownloadReadyResp) GetStorageAddr() string {
	if x != nil {
		return x.StorageAddr
	}
	return ""
}

func (x *StreamDownloadReadyResp) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StreamDownloadReadyResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StreamDownloadReadyResp) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *StreamDownloadReadyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamDownloadReadyResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StreamDownloadReadyResp) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type StreamStoreAckMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,7,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStoreAckMsg) Reset() {
	*x = StreamStoreAckMsg{}
	mi := &file_proto_node_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStoreAckMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStoreAckMsg) ProtoMessage() {}

func (x *StreamStoreAckMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStoreAckMsg.ProtoReflect.Descriptor instead.
func (*StreamStoreAckMsg) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{29}
}

func (x *StreamStoreAckMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamStoreAckMsg) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StreamStoreAckMsg) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *StreamStoreAckMsg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StreamStoreAckMsg) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamStoreAckMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StreamStoreAckMsg) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type StreamUploadReadyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	LogicalTime   int32                  `protobuf:"varint,6,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUploadReadyMsg) Reset() {
	*x = StreamUploadReadyMsg{}
	mi := &file_proto_node_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUploadReadyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUploadReadyMsg) ProtoMessage() {}

func (x *StreamUploadReadyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUploadReadyMsg.ProtoReflect.Descriptor instead.
func (*StreamUploadReadyMsg) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{30}
}

func (x *StreamUploadReadyMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamUploadReadyMsg) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StreamUploadReadyMsg) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StreamUploadReadyMsg) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *StreamUploadReadyMsg) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StreamUploadReadyMsg) GetLogicalTime() int32 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\x03dfs\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xe9\x01\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12!\n" +
	"\x04role\x18\x04 \x01(\x0e2\r.dfs.NodeRoleR\x04role\x12'\n" +
	"\x06status\x18\x05 \x01(\x0e2\x0f.dfs.NodeStatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12A\n" +
	"\x0elast_heartbeat\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"a\n" +
	"\x10HeartbeatRequest\x12*\n" +
	"\tnode_info\x18\x01 \x01(\v2\r.dfs.NodeInfoR\bnodeInfo\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x05R\vlogicalTime\"y\n" +
	"\x0fElectionRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12*\n" +
	"\tnode_info\x18\x02 \x01(\v2\r.dfs.NodeInfoR\bnodeInfo\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x05R\vlogicalTime\"N\n" +
	"\x10ElectionResponse\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x05R\vlogicalTime\"P\n" +
	"\x12CoordinatorRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x05R\vlogicalTime\"N\n" +
	"\x10DiscoveryRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x05R\vlogicalTime\"[\n" +
	"\x11DiscoveryResponse\x12#\n" +
	"\x05peers\x18\x01 \x03(\v2\r.dfs.NodeInfoR\x05peers\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x05R\vlogicalTime\"b\n" +
	"\x11NodeJoinedRequest\x12*\n" +
	"\tnode_info\x18\x01 \x01(\v2\r.dfs.NodeInfoR\bnodeInfo\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x05R\vlogicalTime\"M\n" +
	"\x0fNodeLeftRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x05R\vlogicalTime\"\xd5\x01\n" +
	"\x0eLockRequestMsg\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x05R\vlogicalTime\x12'\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0f.dfs.LockStatusR\x06status\x12=\n" +
	"\frequested_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"f\n" +
	"\aLockAck\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x05R\vlogicalTime\"n\n" +
	"\x0fLockAcquiredMsg\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x05R\vlogicalTime\"m\n" +
	"\x0eLockReleaseMsg\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x05R\vlogicalTime\"J\n" +
	"\fLockAbortMsg\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x05R\vlogicalTime\"c\n" +
	"\x11FileDeleteRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x05R\vlogicalTime\"\xb5\x01\n" +
	"\x10FileStoreRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12!\n" +
	"\flogical_time\x18\x06 \x01(\x05R\vlogicalTime\"@\n" +
	"\x11FileStoreResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"h\n" +
	"\vMetadataReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x05R\vlogicalTime\"\x92\x01\n" +
	"\x10NodeFileMetadata\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"\x96\x01\n" +
	"\fMetadataResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12+\n" +
	"\x05files\x18\x03 \x03(\v2\x15.dfs.NodeFileMetadataR\x05files\x12!\n" +
	"\flogical_time\x18\x04 \x01(\x05R\vlogicalTime\"\xc2\x01\n" +
	"\x10ReplicateFileReq\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1f\n" +
	"\vsource_node\x18\x04 \x01(\tR\n" +
	"sourceNode\x12!\n" +
	"\ftarget_nodes\x18\x05 \x03(\tR\vtargetNodes\x12!\n" +
	"\flogical_time\x18\x06 \x01(\x05R\vlogicalTime\"\x81\x01\n" +
	"\x10APIFileDeleteReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12!\n" +
	"\flogical_time\x18\x04 \x01(\x05R\vlogicalTime\"\x85\x01\n" +
	"\x11APIFileDeleteResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12!\n" +
	"\flogical_time\x18\x04 \x01(\x05R\vlogicalTime\">\n" +
	"\x0fStorageNodeAddr\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"\xdc\x01\n" +
	"\x13StreamUploadInitReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x17\n" +
	"\afrom_id\x18\x06 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\a \x01(\x05R\vlogicalTime\"\xe3\x01\n" +
	"\x15StreamUploadReadyResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x129\n" +
	"\rstorage_nodes\x18\x03 \x03(\v2\x14.dfs.StorageNodeAddrR\fstorageNodes\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12!\n" +
	"\flogical_time\x18\x06 \x01(\x05R\vlogicalTime\"\x9f\x01\n" +
	"\x15StreamDownloadInitReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x17\n" +
	"\afrom_id\x18\x04 \x01(\tR\x06fromId\x12!\n" +
	"\flogical_time\x18\x05 \x01(\x05R\vlogicalTime\"\xf2\x01\n" +
	"\x17StreamDownloadReadyResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fstorage_addr\x18\x02 \x01(\tR\vstorageAddr\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12!\n" +
	"\flogical_time\x18\b \x01(\x05R\vlogicalTime\"\xcb\x01\n" +
	"\x11StreamStoreAckMsg\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12!\n" +
	"\flogical_time\x18\a \x01(\x05R\vlogicalTime\"\xc4\x01\n" +
	"\x14StreamUploadReadyMsg\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12!\n" +
	"\flogical_time\x18\x06 \x01(\x05R\vlogicalTime*R\n" +
	"\bNodeRole\x12\x19\n" +
	"\x15NODE_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_ROLE_MASTER\x10\x01\x12\x15\n" +
	"\x11NODE_ROLE_STORAGE\x10\x02*\x8e\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x02\x12\x18\n" +
	"\x14NODE_STATUS_STARTING\x10\x03\x12\x18\n" +
	"\x14NODE_STATUS_STOPPING\x10\x04*u\n" +
	"\n" +
	"LockStatus\x12\x1b\n" +
	"\x17LOCK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13LOCK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13LOCK_STATUS_GRANTED\x10\x02\x12\x18\n" +
	"\x14LOCK_STATUS_RELEASED\x10\x032\xa7\b\n" +
	"\vNodeService\x12.\n" +
	"\tHeartbeat\x12\x15.dfs.HeartbeatRequest\x1a\n" +
	".dfs.Empty\x127\n" +
	"\bElection\x12\x14.dfs.ElectionRequest\x1a\x15.dfs.ElectionResponse\x122\n" +
	"\vCoordinator\x12\x17.dfs.CoordinatorRequest\x1a\n" +
	".dfs.Empty\x12:\n" +
	"\tDiscovery\x12\x15.dfs.DiscoveryRequest\x1a\x16.dfs.DiscoveryResponse\x120\n" +
	"\n" +
	"NodeJoined\x12\x16.dfs.NodeJoinedRequest\x1a\n" +
	".dfs.Empty\x12,\n" +
	"\bNodeLeft\x12\x14.dfs.NodeLeftRequest\x1a\n" +
	".dfs.Empty\x120\n" +
	"\vRequestLock\x12\x13.dfs.LockRequestMsg\x1a\f.dfs.LockAck\x12/\n" +
	"\vAcquireLock\x12\x14.dfs.LockAcquiredMsg\x1a\n" +
	".dfs.Empty\x12.\n" +
	"\vReleaseLock\x12\x13.dfs.LockReleaseMsg\x1a\n" +
	".dfs.Empty\x12*\n" +
	"\tAbortLock\x12\x11.dfs.LockAbortMsg\x1a\n" +
	".dfs.Empty\x120\n" +
	"\n" +
	"DeleteFile\x12\x16.dfs.FileDeleteRequest\x1a\n" +
	".dfs.Empty\x12:\n" +
	"\tStoreFile\x12\x15.dfs.FileStoreRequest\x1a\x16.dfs.FileStoreResponse\x122\n" +
	"\vGetMetadata\x12\x10.dfs.MetadataReq\x1a\x11.dfs.MetadataResp\x122\n" +
	"\rReplicateFile\x12\x15.dfs.ReplicateFileReq\x1a\n" +
	".dfs.Empty\x12>\n" +
	"\rAPIDeleteFile\x12\x15.dfs.APIFileDeleteReq\x1a\x16.dfs.APIFileDeleteResp\x12H\n" +
	"\x10InitStreamUpload\x12\x18.dfs.StreamUploadInitReq\x1a\x1a.dfs.StreamUploadReadyResp\x12N\n" +
	"\x12InitStreamDownload\x12\x1a.dfs.StreamDownloadInitReq\x1a\x1c.dfs.StreamDownloadReadyResp\x124\n" +
	"\x0eStreamStoreAck\x12\x16.dfs.StreamStoreAckMsg\x1a\n" +
	".dfs.Empty\x12:\n" +
	"\x11StreamUploadReady\x12\x19.dfs.StreamUploadReadyMsg\x1a\n" +
	".dfs.EmptyB\x13Z\x11dfs-backend/protob\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_node_proto_goTypes = []any{
	(NodeRole)(0),                   // 0: dfs.NodeRole
	(NodeStatus)(0),                 // 1: dfs.NodeStatus
	(LockStatus)(0),                 // 2: dfs.LockStatus
	(*Empty)(nil),                   // 3: dfs.Empty
	(*NodeInfo)(nil),                // 4: dfs.NodeInfo
	(*HeartbeatRequest)(nil),        // 5: dfs.HeartbeatRequest
	(*ElectionRequest)(nil),         // 6: dfs.ElectionRequest
	(*ElectionResponse)(nil),        // 7: dfs.ElectionResponse
	(*CoordinatorRequest)(nil),      // 8: dfs.CoordinatorRequest
	(*DiscoveryRequest)(nil),        // 9: dfs.DiscoveryRequest
	(*DiscoveryResponse)(nil),       // 10: dfs.DiscoveryResponse
	(*NodeJoinedRequest)(nil),       // 11: dfs.NodeJoinedRequest
	(*NodeLeftRequest)(nil),         // 12: dfs.NodeLeftRequest
	(*LockRequestMsg)(nil),          // 13: dfs.LockRequestMsg
	(*LockAck)(nil),                 // 14: dfs.LockAck
	(*LockAcquiredMsg)(nil),         // 15: dfs.LockAcquiredMsg
	(*LockReleaseMsg)(nil),          // 16: dfs.LockReleaseMsg
	(*LockAbortMsg)(nil),            // 17: dfs.LockAbortMsg
	(*FileDeleteRequest)(nil),       // 18: dfs.FileDeleteRequest
	(*FileStoreRequest)(nil),        // 19: dfs.FileStoreRequest
	(*FileStoreResponse)(nil),       // 20: dfs.FileStoreResponse
	(*MetadataReq)(nil),             // 21: dfs.MetadataReq
	(*NodeFileMetadata)(nil),        // 22: dfs.NodeFileMetadata
	(*MetadataResp)(nil),            // 23: dfs.MetadataResp
	(*ReplicateFileReq)(nil),        // 24: dfs.ReplicateFileReq
	(*APIFileDeleteReq)(nil),        // 25: dfs.APIFileDeleteReq
	(*APIFileDeleteResp)(nil),       // 26: dfs.APIFileDeleteResp
	(*StorageNodeAddr)(nil),         // 27: dfs.StorageNodeAddr
	(*StreamUploadInitReq)(nil),     // 28: dfs.StreamUploadInitReq
	(*StreamUploadReadyResp)(nil),   // 29: dfs.StreamUploadReadyResp
	(*StreamDownloadInitReq)(nil),   // 30: dfs.StreamDownloadInitReq
	(*StreamDownloadReadyResp)(nil), // 31: dfs.StreamDownloadReadyResp
	(*StreamStoreAckMsg)(nil),       // 32: dfs.StreamStoreAckMsg
	(*StreamUploadReadyMsg)(nil),    // 33: dfs.StreamUploadReadyMsg
	(*timestamp.Timestamp)(nil),     // 34: google.protobuf.Timestamp
}
var file_proto_node_proto_depIdxs = []int32{
	0,  // 0: dfs.NodeInfo.role:type_name -> dfs.NodeRole
	1,  // 1: dfs.NodeInfo.status:type_name -> dfs.NodeStatus
	34, // 2: dfs.NodeInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	4,  // 3: dfs.HeartbeatRequest.node_info:type_name -> dfs.NodeInfo
	4,  // 4: dfs.ElectionRequest.node_info:type_name -> dfs.NodeInfo
	4,  // 5: dfs.DiscoveryResponse.peers:type_name -> dfs.NodeInfo
	4,  // 6: dfs.NodeJoinedRequest.node_info:type_name -> dfs.NodeInfo
	2,  // 7: dfs.LockRequestMsg.status:type_name -> dfs.LockStatus
	34, // 8: dfs.LockRequestMsg.requested_at:type_name -> google.protobuf.Timestamp
	22, // 9: dfs.MetadataResp.files:type_name -> dfs.NodeFileMetadata
	27, // 10: dfs.StreamUploadReadyResp.storage_nodes:type_name -> dfs.StorageNodeAddr
	5,  // 11: dfs.NodeService.Heartbeat:input_type -> dfs.HeartbeatRequest
	6,  // 12: dfs.NodeService.Election:input_type -> dfs.ElectionRequest
	8,  // 13: dfs.NodeService.Coordinator:input_type -> dfs.CoordinatorRequest
	9,  // 14: dfs.NodeService.Discovery:input_type -> dfs.DiscoveryRequest
	11, // 15: dfs.NodeService.NodeJoined:input_type -> dfs.NodeJoinedRequest
	12, // 16: dfs.NodeService.NodeLeft:input_type -> dfs.NodeLeftRequest
	13, // 17: dfs.NodeService.RequestLock:input_type -> dfs.LockRequestMsg
	15, // 18: dfs.NodeService.AcquireLock:input_type -> dfs.LockAcquiredMsg
	16, // 19: dfs.NodeService.ReleaseLock:input_type -> dfs.LockReleaseMsg
	17, // 20: dfs.NodeService.AbortLock:input_type -> dfs.LockAbortMsg
	18, // 21: dfs.NodeService.DeleteFile:input_type -> dfs.FileDeleteRequest
	19, // 22: dfs.NodeService.StoreFile:input_type -> dfs.FileStoreRequest
	21, // 23: dfs.NodeService.GetMetadata:input_type -> dfs.MetadataReq
	24, // 24: dfs.NodeService.ReplicateFile:input_type -> dfs.ReplicateFileReq
	25, // 25: dfs.NodeService.APIDeleteFile:input_type -> dfs.APIFileDeleteReq
	28, // 26: dfs.NodeService.InitStreamUpload:input_type -> dfs.StreamUploadInitReq
	30, // 27: dfs.NodeService.InitStreamDownload:input_type -> dfs.StreamDownloadInitReq
	32, // 28: dfs.NodeService.StreamStoreAck:input_type -> dfs.StreamStoreAckMsg
	33, // 29: dfs.NodeService.StreamUploadReady:input_type -> dfs.StreamUploadReadyMsg
	3,  // 30: dfs.NodeService.Heartbeat:output_type -> dfs.Empty
	7,  // 31: dfs.NodeService.Election:output_type -> dfs.ElectionResponse
	3,  // 32: dfs.NodeService.Coordinator:output_type -> dfs.Empty
	10, // 33: dfs.NodeService.Discovery:output_type -> dfs.DiscoveryResponse
	3,  // 34: dfs.NodeService.NodeJoined:output_type -> dfs.Empty
	3,  // 35: dfs.NodeService.NodeLeft:output_type -> dfs.Empty
	14, // 36: dfs.NodeService.RequestLock:output_type -> dfs.LockAck
	3,  // 37: dfs.NodeService.AcquireLock:output_type -> dfs.Empty
	3,  // 38: dfs.NodeService.ReleaseLock:output_type -> dfs.Empty
	3,  // 39: dfs.NodeService.AbortLock:output_type -> dfs.Empty
	3,  // 40: dfs.NodeService.DeleteFile:output_type -> dfs.Empty
	20, // 41: dfs.NodeService.StoreFile:output_type -> dfs.FileStoreResponse
	23, // 42: dfs.NodeService.GetMetadata:output_type -> dfs.MetadataResp
	3,  // 43: dfs.NodeService.ReplicateFile:output_type -> dfs.Empty
	26, // 44: dfs.NodeService.APIDeleteFile:output_type -> dfs.APIFileDeleteResp
	29, // 45: dfs.NodeService.InitStreamUpload:output_type -> dfs.StreamUploadReadyResp
	31, // 46: dfs.NodeService.InitStreamDownload:output_type -> dfs.StreamDownloadReadyResp
	3,  // 47: dfs.NodeService.StreamStoreAck:output_type -> dfs.Empty
	3,  // 48: dfs.NodeService.StreamUploadReady:output_type -> dfs.Empty
	30, // [30:49] is the sub-list for method output_type
	11, // [11:30] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		EnumInfos:         file_proto_node_proto_enumTypes,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
