// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: proto/node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Heartbeat_FullMethodName          = "/dfs.NodeService/Heartbeat"
	NodeService_Election_FullMethodName           = "/dfs.NodeService/Election"
	NodeService_Coordinator_FullMethodName        = "/dfs.NodeService/Coordinator"
	NodeService_Discovery_FullMethodName          = "/dfs.NodeService/Discovery"
	NodeService_NodeJoined_FullMethodName         = "/dfs.NodeService/NodeJoined"
	NodeService_NodeLeft_FullMethodName           = "/dfs.NodeService/NodeLeft"
	NodeService_RequestLock_FullMethodName        = "/dfs.NodeService/RequestLock"
	NodeService_AcquireLock_FullMethodName        = "/dfs.NodeService/AcquireLock"
	NodeService_ReleaseLock_FullMethodName        = "/dfs.NodeService/ReleaseLock"
	NodeService_AbortLock_FullMethodName          = "/dfs.NodeService/AbortLock"
	NodeService_DeleteFile_FullMethodName         = "/dfs.NodeService/DeleteFile"
	NodeService_StoreFile_FullMethodName          = "/dfs.NodeService/StoreFile"
	NodeService_GetMetadata_FullMethodName        = "/dfs.NodeService/GetMetadata"
	NodeService_ReplicateFile_FullMethodName      = "/dfs.NodeService/ReplicateFile"
	NodeService_APIDeleteFile_FullMethodName      = "/dfs.NodeService/APIDeleteFile"
	NodeService_InitStreamUpload_FullMethodName   = "/dfs.NodeService/InitStreamUpload"
	NodeService_InitStreamDownload_FullMethodName = "/dfs.NodeService/InitStreamDownload"
	NodeService_StreamStoreAck_FullMethodName     = "/dfs.NodeService/StreamStoreAck"
	NodeService_StreamUploadReady_FullMethodName  = "/dfs.NodeService/StreamUploadReady"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// Heartbeat - periodic health check between nodes
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error)
	// Election - Bully algorithm messages
	Election(ctx context.Context, in *ElectionRequest, opts ...grpc.CallOption) (*ElectionResponse, error)
	Coordinator(ctx context.Context, in *CoordinatorRequest, opts ...grpc.CallOption) (*Empty, error)
	// Discovery - peer discovery
	Discovery(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
	// Node membership
	NodeJoined(ctx context.Context, in *NodeJoinedRequest, opts ...grpc.CallOption) (*Empty, error)
	NodeLeft(ctx context.Context, in *NodeLeftRequest, opts ...grpc.CallOption) (*Empty, error)
	// Distributed locking
	RequestLock(ctx context.Context, in *LockRequestMsg, opts ...grpc.CallOption) (*LockAck, error)
	AcquireLock(ctx context.Context, in *LockAcquiredMsg, opts ...grpc.CallOption) (*Empty, error)
	ReleaseLock(ctx context.Context, in *LockReleaseMsg, opts ...grpc.CallOption) (*Empty, error)
	AbortLock(ctx context.Context, in *LockAbortMsg, opts ...grpc.CallOption) (*Empty, error)
	// File operations
	DeleteFile(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	StoreFile(ctx context.Context, in *FileStoreRequest, opts ...grpc.CallOption) (*FileStoreResponse, error)
	// Metadata sync
	GetMetadata(ctx context.Context, in *MetadataReq, opts ...grpc.CallOption) (*MetadataResp, error)
	// File replication
	ReplicateFile(ctx context.Context, in *ReplicateFileReq, opts ...grpc.CallOption) (*Empty, error)
	// API file delete (master handles this)
	APIDeleteFile(ctx context.Context, in *APIFileDeleteReq, opts ...grpc.CallOption) (*APIFileDeleteResp, error)
	// Streaming session coordination
	InitStreamUpload(ctx context.Context, in *StreamUploadInitReq, opts ...grpc.CallOption) (*StreamUploadReadyResp, error)
	InitStreamDownload(ctx context.Context, in *StreamDownloadInitReq, opts ...grpc.CallOption) (*StreamDownloadReadyResp, error)
	StreamStoreAck(ctx context.Context, in *StreamStoreAckMsg, opts ...grpc.CallOption) (*Empty, error)
	StreamUploadReady(ctx context.Context, in *StreamUploadReadyMsg, opts ...grpc.CallOption) (*Empty, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Election(ctx context.Context, in *ElectionRequest, opts ...grpc.CallOption) (*ElectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElectionResponse)
	err := c.cc.Invoke(ctx, NodeService_Election_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Coordinator(ctx context.Context, in *CoordinatorRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_Coordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Discovery(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, NodeService_Discovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NodeJoined(ctx context.Context, in *NodeJoinedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_NodeJoined_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NodeLeft(ctx context.Context, in *NodeLeftRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_NodeLeft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RequestLock(ctx context.Context, in *LockRequestMsg, opts ...grpc.CallOption) (*LockAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockAck)
	err := c.cc.Invoke(ctx, NodeService_RequestLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AcquireLock(ctx context.Context, in *LockAcquiredMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReleaseLock(ctx context.Context, in *LockReleaseMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AbortLock(ctx context.Context, in *LockAbortMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_AbortLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteFile(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StoreFile(ctx context.Context, in *FileStoreRequest, opts ...grpc.CallOption) (*FileStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileStoreResponse)
	err := c.cc.Invoke(ctx, NodeService_StoreFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetMetadata(ctx context.Context, in *MetadataReq, opts ...grpc.CallOption) (*MetadataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResp)
	err := c.cc.Invoke(ctx, NodeService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReplicateFile(ctx context.Context, in *ReplicateFileReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_ReplicateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) APIDeleteFile(ctx context.Context, in *APIFileDeleteReq, opts ...grpc.CallOption) (*APIFileDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIFileDeleteResp)
	err := c.cc.Invoke(ctx, NodeService_APIDeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) InitStreamUpload(ctx context.Context, in *StreamUploadInitReq, opts ...grpc.CallOption) (*StreamUploadReadyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamUploadReadyResp)
	err := c.cc.Invoke(ctx, NodeService_InitStreamUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) InitStreamDownload(ctx context.Context, in *StreamDownloadInitReq, opts ...grpc.CallOption) (*StreamDownloadReadyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamDownloadReadyResp)
	err := c.cc.Invoke(ctx, NodeService_InitStreamDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamStoreAck(ctx context.Context, in *StreamStoreAckMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_StreamStoreAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamUploadReady(ctx context.Context, in *StreamUploadReadyMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_StreamUploadReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	// Heartbeat - periodic health check between nodes
	Heartbeat(context.Context, *HeartbeatRequest) (*Empty, error)
	// Election - Bully algorithm messages
	Election(context.Context, *ElectionRequest) (*ElectionResponse, error)
	Coordinator(context.Context, *CoordinatorRequest) (*Empty, error)
	// Discovery - peer discovery
	Discovery(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
	// Node membership
	NodeJoined(context.Context, *NodeJoinedRequest) (*Empty, error)
	NodeLeft(context.Context, *NodeLeftRequest) (*Empty, error)
	// Distributed locking
	RequestLock(context.Context, *LockRequestMsg) (*LockAck, error)
	AcquireLock(context.Context, *LockAcquiredMsg) (*Empty, error)
	ReleaseLock(context.Context, *LockReleaseMsg) (*Empty, error)
	AbortLock(context.Context, *LockAbortMsg) (*Empty, error)
	// File operations
	DeleteFile(context.Context, *FileDeleteRequest) (*Empty, error)
	StoreFile(context.Context, *FileStoreRequest) (*FileStoreResponse, error)
	// Metadata sync
	GetMetadata(context.Context, *MetadataReq) (*MetadataResp, error)
	// File replication
	ReplicateFile(context.Context, *ReplicateFileReq) (*Empty, error)
	// API file delete (master handles this)
	APIDeleteFile(context.Context, *APIFileDeleteReq) (*APIFileDeleteResp, error)
	// Streaming session coordination
	InitStreamUpload(context.Context, *StreamUploadInitReq) (*StreamUploadReadyResp, error)
	InitStreamDownload(context.Context, *StreamDownloadInitReq) (*StreamDownloadReadyResp, error)
	StreamStoreAck(context.Context, *StreamStoreAckMsg) (*Empty, error)
	StreamUploadReady(context.Context, *StreamUploadReadyMsg) (*Empty, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeServiceServer) Election(context.Context, *ElectionRequest) (*ElectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Election not implemented")
}
func (UnimplementedNodeServiceServer) Coordinator(context.Context, *CoordinatorRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Coordinator not implemented")
}
func (UnimplementedNodeServiceServer) Discovery(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Discovery not implemented")
}
func (UnimplementedNodeServiceServer) NodeJoined(context.Context, *NodeJoinedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeJoined not implemented")
}
func (UnimplementedNodeServiceServer) NodeLeft(context.Context, *NodeLeftRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeLeft not implemented")
}
func (UnimplementedNodeServiceServer) RequestLock(context.Context, *LockRequestMsg) (*LockAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestLock not implemented")
}
func (UnimplementedNodeServiceServer) AcquireLock(context.Context, *LockAcquiredMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedNodeServiceServer) ReleaseLock(context.Context, *LockReleaseMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedNodeServiceServer) AbortLock(context.Context, *LockAbortMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortLock not implemented")
}
func (UnimplementedNodeServiceServer) DeleteFile(context.Context, *FileDeleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedNodeServiceServer) StoreFile(context.Context, *FileStoreRequest) (*FileStoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedNodeServiceServer) GetMetadata(context.Context, *MetadataReq) (*MetadataResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedNodeServiceServer) ReplicateFile(context.Context, *ReplicateFileReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateFile not implemented")
}
func (UnimplementedNodeServiceServer) APIDeleteFile(context.Context, *APIFileDeleteReq) (*APIFileDeleteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method APIDeleteFile not implemented")
}
func (UnimplementedNodeServiceServer) InitStreamUpload(context.Context, *StreamUploadInitReq) (*StreamUploadReadyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InitStreamUpload not implemented")
}
func (UnimplementedNodeServiceServer) InitStreamDownload(context.Context, *StreamDownloadInitReq) (*StreamDownloadReadyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InitStreamDownload not implemented")
}
func (UnimplementedNodeServiceServer) StreamStoreAck(context.Context, *StreamStoreAckMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StreamStoreAck not implemented")
}
func (UnimplementedNodeServiceServer) StreamUploadReady(context.Context, *StreamUploadReadyMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StreamUploadReady not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Election_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Election(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Election_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Election(ctx, req.(*ElectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Coordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Coordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Coordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Coordinator(ctx, req.(*CoordinatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Discovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Discovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Discovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Discovery(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NodeJoined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeJoinedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NodeJoined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_NodeJoined_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NodeJoined(ctx, req.(*NodeJoinedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NodeLeft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeLeftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NodeLeft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_NodeLeft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NodeLeft(ctx, req.(*NodeLeftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RequestLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RequestLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RequestLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RequestLock(ctx, req.(*LockRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockAcquiredMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AcquireLock(ctx, req.(*LockAcquiredMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockReleaseMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReleaseLock(ctx, req.(*LockReleaseMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AbortLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockAbortMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AbortLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_AbortLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AbortLock(ctx, req.(*LockAbortMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteFile(ctx, req.(*FileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StoreFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StoreFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StoreFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StoreFile(ctx, req.(*FileStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetMetadata(ctx, req.(*MetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReplicateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReplicateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReplicateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReplicateFile(ctx, req.(*ReplicateFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_APIDeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIFileDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).APIDeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_APIDeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).APIDeleteFile(ctx, req.(*APIFileDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_InitStreamUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamUploadInitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).InitStreamUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_InitStreamUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).InitStreamUpload(ctx, req.(*StreamUploadInitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_InitStreamDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamDownloadInitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).InitStreamDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_InitStreamDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).InitStreamDownload(ctx, req.(*StreamDownloadInitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamStoreAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamStoreAckMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StreamStoreAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StreamStoreAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StreamStoreAck(ctx, req.(*StreamStoreAckMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamUploadReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamUploadReadyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StreamUploadReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StreamUploadReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StreamUploadReady(ctx, req.(*StreamUploadReadyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _NodeService_Heartbeat_Handler,
		},
		{
			MethodName: "Election",
			Handler:    _NodeService_Election_Handler,
		},
		{
			MethodName: "Coordinator",
			Handler:    _NodeService_Coordinator_Handler,
		},
		{
			MethodName: "Discovery",
			Handler:    _NodeService_Discovery_Handler,
		},
		{
			MethodName: "NodeJoined",
			Handler:    _NodeService_NodeJoined_Handler,
		},
		{
			MethodName: "NodeLeft",
			Handler:    _NodeService_NodeLeft_Handler,
		},
		{
			MethodName: "RequestLock",
			Handler:    _NodeService_RequestLock_Handler,
		},
		{
			MethodName: "AcquireLock",
			Handler:    _NodeService_AcquireLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _NodeService_ReleaseLock_Handler,
		},
		{
			MethodName: "AbortLock",
			Handler:    _NodeService_AbortLock_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _NodeService_DeleteFile_Handler,
		},
		{
			MethodName: "StoreFile",
			Handler:    _NodeService_StoreFile_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _NodeService_GetMetadata_Handler,
		},
		{
			MethodName: "ReplicateFile",
			Handler:    _NodeService_ReplicateFile_Handler,
		},
		{
			MethodName: "APIDeleteFile",
			Handler:    _NodeService_APIDeleteFile_Handler,
		},
		{
			MethodName: "InitStreamUpload",
			Handler:    _NodeService_InitStreamUpload_Handler,
		},
		{
			MethodName: "InitStreamDownload",
			Handler:    _NodeService_InitStreamDownload_Handler,
		},
		{
			MethodName: "StreamStoreAck",
			Handler:    _NodeService_StreamStoreAck_Handler,
		},
		{
			MethodName: "StreamUploadReady",
			Handler:    _NodeService_StreamUploadReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/node.proto",
}
